### ISSUE TITLE
Sentence fragment

### ISSUE THREAD

**Issue by maswiebe** [PacktPublishing/Bayesian-Analysis-with-Python#3]
There seems to be a sentence fragment in the function description of [hpd_grid](https://github.com/PacktPublishing/Bayesian-Analysis-with-Python/blob/master/Chapter%201/hpd%20(1).py):

>     Returns
>     ----------
>     hpd: array with the lower 

With the lower _what_?

**Comment by aloctavodia** [comment]
Hi, thanks for reporting the mistake is has been fixed in this repository
https://github.com/aloctavodia/BAP/blob/master/first_edition/code/Chp1/hpd.py

**Comment by maswiebe** [comment]
Thanks!
